### ISSUE TITLE
Tests and project build fail to compile on M1 Mac

### ISSUE THREAD

**Issue by tatujan** [onflow/flow-go#1805]
## 🐞 Bug Report

Following through the installation guide, running `make install-tools` works. But jumping on to the compiling and running the tests, almost all fails. When error is checked in detail, we see that build script is trying to link x86_64 files with MacOS-arm64 libraries. So tests can't be compiled and they fail. 

## What is the severity of this bug?

It does not build on M1 Mac.

## Reproduction steps

Steps to reproduce the behaviour:

1. Follow installation guide on an M1 Mac and 
1. Complete steps till `make test` and run `make test`
1. Check error logs. 

## Expected behaviour

Expected unit tests to be compiled and run properly. Did expect tests to pass. 

## Screenshots

<img width="999" alt="Screen Shot 2022-01-04 at 4 19 10 PM" src="https://user-images.githubusercontent.com/7893713/148137043-5960352e-8f40-4df4-9b97-d2a8ecca0e4f.png">

## Specifications

- System: MacBook Pro (13-inch, M1, 2020) MacOS 11.1
- Go: 1.17.5 darwin/arm64

- Apple clang version 12.0.5 (clang-1205.0.22.11) 
- Target: arm64-apple-darwin20.2.0 
- Thread model: posix 
- InstalledDir: /Library/Developer/CommandLineTools/usr/bin

## Additional context
I found this issue similar to #809 but not quite same. As the `make install-tools` works fine but the immediate next step fails, due to incompatibility of the system architecture.

**Comment by tatujan** [comment]
I've looked around a bit. Realized the the relic library does not support arm64. It supports ATMEL 8bit , TI 16 bit, arm32, x86_32 and x86_64 specified in `crypto/relic/cmake/arch.cmake`. So, while trying to build it defaults to x86_64?

**Comment by tatujan** [comment]
I've partially solved the issue. CMake was running with Rosetta2. When I've updated it to the latest version, it switched to arm64 arch. Now most of the tests pass and no linkage error. However now when I run `make integration-test`, it is failing at ` => ERROR [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,  20.3s` step with error log:

` > [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build --tags "relic,netgo" -ldflags "-extldflags -static     -X 'github.com/onflow/flow-go/cmd/build.commit=fb6f8192f00c7a37d2843f6693a7f943df26d335' -X  'github.com/onflow/flow-go/cmd/build.semver=v0.23.1-1208-gfb6f8'"     -o ./app ./cmd/collection:
#23 1.688 # runtime/cgo
#23 1.688 gcc: error: unrecognized command-line option '-m64'
`

any idea?

**Comment by sjonpaulbrown** [comment]
@tatujan In regards to the docker build issue, I also experienced this issue while building on M1 Macbooks. The `GOARCH` env variable in the `go build` command needs to be altered. 

`GOARCH=amd64` on line https://github.com/onflow/flow-go/blob/master/cmd/Dockerfile#L44 can be replaced with `GOARCH=arm64`.

We will need to make this an argument that is passed in during the docker build. This will most likely require some work in our `Makefile` to determine the system architecture before injecting `arm64` or `amd64` in as a docker argument.

For now, to resolve your issue, you can update the `GOARCH=amd64` references in the [Dockerfile](https://github.com/onflow/flow-go/blob/master/cmd/Dockerfile) to `GOARCH=arm64`.

**Comment by tatujan** [comment]
@sjonpaulbrown Yes, I was able to fix it the day I've posted my last comment. Took me a few hours start playing with go build flags and replace `amd64` with `arm64`. Thanks!

**Comment by tatujan** [comment]
Hi @sjonpaulbrown, just pulled the latest changes on master branch. And now I'm having build errors again. Looks like a variable is not defined. Not sure if it's architecture related. Here is the log:

 => ERROR [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,t  0.7s
------
 > [build-production 2/3] RUN --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build --tags "relic,netgo" -ldflags "-extldflags -static     -X 'github.com/onflow/flow-go/cmd/build.commit=eba6e2c975481a2bf76d052735c4bf00acfc542d' -X  'github.com/onflow/flow-go/cmd/build.semver=v0.23.1-1446-geba6e2'"     -o ./app ./cmd/collection:
#21 0.564 # github.com/onflow/flow-go/crypto/hash
#21 0.564 crypto/hash/xor_generic.go:48:15: undefined: sha3State
#21 0.564 crypto/hash/xor_generic.go:59:27: undefined: sha3State
------

Any idea why crypto/hash/xor_generic cannot find sha3State?

**Comment by peterargue** [comment]
the last issue is probably related to https://github.com/onflow/flow-go/pull/1903

**Comment by peterargue** [comment]
@tatujan we just merged 2 PRs (https://github.com/onflow/flow-go/pull/1903, https://github.com/onflow/flow-go/pull/1904) that should help get the dockerized builds and localnet working on M1 machines. Can you give it a try on master?

**Comment by tatujan** [comment]
@peterargue Yes, thank you for the heads up! I've seen the PRs and pulled the last changes. It seems like it builds just fine. Some tests still fail though. Not sure it is because it is still under development or failing due to something else. I can share some logs if you are interested.

**Comment by peterargue** [comment]
The tests should pass. There are some known to be flaky that we're working to fix, particularly some integration tests.

Feel free to submit issues for any you can get to pass. PRs are also welcome!

**Comment by tatujan** [comment]
Issue solved with PR #1945
